<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Machine-Learning - Regression: Linear and Non-Linear</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Machine-Learning</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./prob_and_randvar.html" rel="" target="">
 <span class="menu-text">Probability Theory and Random Variables</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./clustering.html" rel="" target="">
 <span class="menu-text">Clustering: Unraveling Patterns</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./regression.html" rel="" target="" aria-current="page">
 <span class="menu-text">Regression: Linear and Non-Linear</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./classification.html" rel="" target="">
 <span class="menu-text">Classification: Unveiling Insights</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./anomaly.html" rel="" target="">
 <span class="menu-text">Anomaly/Outlier Detection</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link active" data-scroll-target="#linear-regression">Linear Regression</a></li>
  <li><a href="#non-linear-regression" id="toc-non-linear-regression" class="nav-link" data-scroll-target="#non-linear-regression">Non-Linear Regression</a></li>
  <li><a href="#applications-and-visualiations" id="toc-applications-and-visualiations" class="nav-link" data-scroll-target="#applications-and-visualiations">Applications and Visualiations</a></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation">Model Evaluation</a></li>
  <li><a href="#applying-regression" id="toc-applying-regression" class="nav-link" data-scroll-target="#applying-regression">Applying Regression</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression: Linear and Non-Linear</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Machine Learning is a realm filled with diverse algorithms and offers powerful tools for understanding relationships between variables and making predictions. Two fundamental tchniques for regression tasks are linear regression and non-linear regression. In this blog, we will embark on a journry to explore concepts, applications, and implementations of both linear and non-linear regression.</p>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">Linear Regression</h3>
<p>Linear regression is a straightforward yet powerful method for modeling the relationship between a dependent variable (<span class="math inline">\(y\)</span>) and one or more independent variables (<span class="math inline">\(x\)</span>). The relationship is assumed to be linear, meaning that a change in the independent variable(s) results in a proportional change in the dependent variable.</p>
<section id="simple-linear-regression-slr" class="level4">
<h4 class="anchored" data-anchor-id="simple-linear-regression-slr">Simple Linear Regression (SLR)</h4>
<p>In SLR, there is only one independent variable. The relationship can be expressed as:</p>
<p><span class="math display">\[y = \beta_0 + \beta_1 . x + \epsilon\]</span></p>
<p>Where:<br>
</p>
<ul>
<li><span class="math inline">\(y\)</span> is the dependent variable<br>
</li>
<li><span class="math inline">\(x\)</span> is the independent variable<br>
</li>
<li><span class="math inline">\(\beta_0\)</span> is the intercept<br>
</li>
<li><span class="math inline">\(\beta_1\)</span> is the slope<br>
</li>
<li><span class="math inline">\(\epsilon\)</span> is the error term<br>
</li>
</ul>
</section>
<section id="multiple-linear-regression" class="level4">
<h4 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h4>
<p>When there are multiple independent variables, the equation becomes:</p>
<p><span class="math display">\[y = \beta_0 + \beta_1 . x_1 + \beta_2 . x_2 + ... + \beta_n . x_n + \epsilon\]</span></p>
</section>
</section>
<section id="non-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="non-linear-regression">Non-Linear Regression</h3>
<p>Non-linear regression allows for more complex relationships between variables by using non-linear functions to model the data. This is particularly useful when the linear assumptions of relationships breaks down.</p>
<section id="polynomial-regression" class="level4">
<h4 class="anchored" data-anchor-id="polynomial-regression">Polynomial Regression</h4>
<p>Non-linear regression is a form of non-linear regression where the relationship between variables is modeled as an n-th degree polynomial. For a quadratic polynomial:</p>
<p><span class="math display">\[y = \beta_0 + \beta_1.x + \beta_2. x^2 + \epsilon\]</span> #### Exponential and Logarithmic Regression</p>
<p>When the relationship between variables follows an exponential or logarithmic pattern, non-linear regression can capture these relationships effectively.</p>
<p>Exponential Regression: <span class="math inline">\(y = \beta_0 . e^{\beta_1.x} +\epsilon\)</span></p>
<p>Logarithmic Regression: <span class="math inline">\(y = \beta_0 + \beta_1 . ln(x) + \epsilon\)</span></p>
</section>
</section>
<section id="applications-and-visualiations" class="level3">
<h3 class="anchored" data-anchor-id="applications-and-visualiations">Applications and Visualiations</h3>
<section id="real-world-applications" class="level4">
<h4 class="anchored" data-anchor-id="real-world-applications">Real-world Applications</h4>
<p>Linear and non-linear regression find applications in various applications:<br>
</p>
<ul>
<li><strong>Economics</strong>: predicting economic indicators<br>
</li>
<li><strong>Biology</strong>: modeling growth rates of organisms<br>
</li>
<li><strong>Finance</strong>: forecasting stock prices &nbsp;</li>
<li><strong>Engineering</strong>: predicting equipment performance<br>
</li>
</ul>
</section>
</section>
<section id="model-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="model-evaluation">Model Evaluation</h3>
<section id="assessing-model-performance" class="level4">
<h4 class="anchored" data-anchor-id="assessing-model-performance">Assessing Model Performance</h4>
<ul>
<li><p><strong>Mean Squared Error (MSE)</strong>: measures the average squared difference between predicted and actual values<br>
</p></li>
<li><p><strong>R-squared (</strong><span class="math inline">\(R^2\)</span>): indicates the proportion of the variance in the dependen variable that is predictable from the independent variable(s)</p></li>
</ul>
</section>
</section>
<section id="applying-regression" class="level3">
<h3 class="anchored" data-anchor-id="applying-regression">Applying Regression</h3>
<p>Next, we are going to apply some linear and non-linear algorithms on a dataset - <strong>Advertising Dataset</strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'olsrr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:datasets':

    rivers</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ dplyr::recode() masks car::recode()
✖ purrr::some()   masks car::some()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
Loading required package: lattice


Attaching package: 'caret'


The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     TV Radio Newspaper Sales
1 230.1  37.8      69.2  22.1
2  44.5  39.3      45.1  10.4
3  17.2  45.9      69.3  12.0
4 151.5  41.3      58.5  16.5
5 180.8  10.8      58.4  17.9
6   8.7  48.9      75.0   7.2</code></pre>
</div>
</div>
<p>An important aspect of regression problems is deciding the target and predictors. This does vary based on the problem at hand or the research questions one is trying to answer. With this data, let’s say we want to use <strong>Sales</strong> as the <strong>Target</strong> variable and <strong>TV, Radio, Newspaper</strong> as <strong>Predictors</strong>.</p>
<p>Looking at the scatter plot matrix between each fields in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(data, <span class="at">upper.panel =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Scatter plots help get sense of correlation between field, which is an important metric for regression. We can see that that TV and Radio, and TV and Newspaper have low correlations. We can also observe that there is a high correlation between TV and Sales, Radio and Sales and Newspaper and Sales.</p>
<section id="splitting-dataset-and-modeling" class="level4">
<h4 class="anchored" data-anchor-id="splitting-dataset-and-modeling">Splitting Dataset and Modeling</h4>
<p>Next, we split that dataset into train and test splits. We use the training set first to fit the model and then use the testing set to check the performance of the obtained model. We will randomly split the data here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>training_samples <span class="ot">&lt;-</span> data<span class="sc">$</span>Sales <span class="sc">%&gt;%</span> <span class="fu">createDataPartition</span>(<span class="at">p =</span> <span class="fl">0.75</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> data[training_samples, ]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> data[<span class="sc">-</span>training_samples, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-simple-linear-regression" class="level4">
<h4 class="anchored" data-anchor-id="fitting-simple-linear-regression">Fitting Simple Linear Regression</h4>
<p>Three different models using the three predictors and we will look at the <strong>Adjusted R2</strong> to find the percentage variance explained by these models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>slr1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> TV, <span class="at">data=</span>train)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ TV, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.4110 -1.7007  0.2769  1.6356  5.7615 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.820068   0.391697   17.41   &lt;2e-16 ***
TV          0.055899   0.002285   24.46   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.391 on 149 degrees of freedom
Multiple R-squared:  0.8006,    Adjusted R-squared:  0.7993 
F-statistic: 598.4 on 1 and 149 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>slr2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> Radio, <span class="at">data=</span>train)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ Radio, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.9359  -3.5593   0.6252   4.2129   8.1901 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 12.01533    0.72633  16.542  &lt; 2e-16 ***
Radio        0.13941    0.02704   5.156 7.91e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.932 on 149 degrees of freedom
Multiple R-squared:  0.1514,    Adjusted R-squared:  0.1457 
F-statistic: 26.58 on 1 and 149 DF,  p-value: 7.907e-07</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>slr3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> Newspaper, <span class="at">data=</span>train)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ Newspaper, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.5497  -3.8956   0.6684   3.7927  11.4179 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13.75564    0.73181  18.797   &lt;2e-16 ***
Newspaper    0.04530    0.01947   2.326   0.0214 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.26 on 149 degrees of freedom
Multiple R-squared:  0.03504,   Adjusted R-squared:  0.02857 
F-statistic: 5.411 on 1 and 149 DF,  p-value: 0.02136</code></pre>
</div>
</div>
<p>The first model, with TV as the predictor, explains approximately <strong>80%</strong> of variablity of the target with a residual standard error of <strong>2.39</strong>. The second model, with Radio as the predictor, explains <strong>15%</strong> of variability of the target with an error of <strong>4.93%</strong>. The third model, with Newspaper as the predictor, explains <strong>3%</strong> of variability of the target with an error of <strong>5.26%</strong>.</p>
<p>Clearly, TV as a predictor is explaining more variability of target. However, using a single plot means we might completely neglec the effect of the other two predictors on Sales.</p>
</section>
<section id="fitting-multiple-linear-regression" class="level4">
<h4 class="anchored" data-anchor-id="fitting-multiple-linear-regression">Fitting Multiple Linear Regression</h4>
<p>There are multiple methods to extend a simple linear regression. But since, we have only three predictors to work with, we will use a <strong>Forward Selection Method</strong> to explore more models.</p>
<p>Since, TV as a predictor explained most variability(<strong>80%</strong>) earlier, we can add Radio as the two predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mlr1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> TV <span class="sc">+</span> Radio, <span class="at">data=</span>train)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ TV + Radio, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.4365 -0.8185 -0.0393  0.8595  3.7890 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.585300   0.341251   13.44   &lt;2e-16 ***
TV          0.054150   0.001658   32.66   &lt;2e-16 ***
Radio       0.111447   0.009508   11.72   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.727 on 148 degrees of freedom
Multiple R-squared:  0.8966,    Adjusted R-squared:  0.8952 
F-statistic: 641.8 on 2 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We can notice that the <strong>Adjusted R2</strong> has improved to <strong>89%</strong>. Having said that, we need to check that the imporovement is statistically significant. For this, we will use Analysis of Variance (ANOVA) to test the null hypothesis - <strong>H0: The improvement is not significantly significant</strong> and <strong>H1 - The improvement is statisitically significant</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(slr1, mlr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Sales ~ TV
Model 2: Sales ~ TV + Radio
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    149 851.61                                  
2    148 441.63  1    409.98 137.39 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The p-value is significantly less than 0.05, and therefore we have sufficient evidence to reject the null hypothesis and accept the alternative.</p>
<p>We can try to extend the model further with using <strong>Newspaper</strong> as a third predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mlr2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> TV <span class="sc">+</span> Radio <span class="sc">+</span> Newspaper, <span class="at">data=</span>train)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ TV + Radio + Newspaper, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.4167 -0.8112 -0.0623  0.8476  3.7868 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.5730056  0.3618831  12.637   &lt;2e-16 ***
TV          0.0541379  0.0016672  32.472   &lt;2e-16 ***
Radio       0.1110996  0.0100967  11.004   &lt;2e-16 ***
Newspaper   0.0007159  0.0068211   0.105    0.917    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.733 on 147 degrees of freedom
Multiple R-squared:  0.8966,    Adjusted R-squared:  0.8945 
F-statistic:   425 on 3 and 147 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Looking at the p-value for Newspaper as a predictor, it deems not statistically significant (0.917 &gt; 0.05). Adjusted R2 changed from <strong>89.52</strong> to <strong>89.45</strong>. For these reasons, we have evidence to not include Newspaper as a predictor in the model.</p>
</section>
<section id="fitting-orthogonal-polynomial-regression" class="level4">
<h4 class="anchored" data-anchor-id="fitting-orthogonal-polynomial-regression">Fitting Orthogonal Polynomial Regression</h4>
<p>All the assumptions of Multiple Linear Regression were checked and the conclusion was that variance is constant. One last possibility is to check if there is any non-linear relationship between the target and predictors. From the scatter plot, we looked at the beginning, we have noticed that there is some type of curvilinear relationship. For this, we will be using a Polynomial Regression. We will look at specifically <strong>Orthogonal Polynomial Regression between Sales and predictors TV and Radio</strong>. We already know that Newspaper is not a statistically significant predictor, so we won’t be using Newspaper as a predictor for the non-linear regression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>opr1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> <span class="fu">poly</span>(TV, <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">poly</span>(Radio, <span class="dv">2</span>) <span class="sc">+</span> TV<span class="sc">:</span>Radio, <span class="at">data=</span>train)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(opr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ poly(TV, 2) + poly(Radio, 2) + TV:Radio, 
    data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8681 -0.7959 -0.0245  0.7578  3.3478 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      1.354e+01  3.358e-01  40.307  &lt; 2e-16 ***
poly(TV, 2)1     4.484e+01  2.663e+00  16.835  &lt; 2e-16 ***
poly(TV, 2)2    -9.000e+00  1.414e+00  -6.365 2.41e-09 ***
poly(Radio, 2)1  8.346e+00  2.937e+00   2.841  0.00514 ** 
poly(Radio, 2)2  3.440e+00  1.427e+00   2.410  0.01719 *  
TV:Radio         4.649e-04  9.167e-05   5.071 1.19e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.404 on 145 degrees of freedom
Multiple R-squared:  0.9331,    Adjusted R-squared:  0.9308 
F-statistic: 404.4 on 5 and 145 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>As seen in the last line of output, this model is statistically significant since p-value &lt;&lt;&lt; 0.5. All the coefficients are statistically significant since all p-value are &lt;&lt;&lt; 0.5. This second order orthogonal polynomial model explains <strong>93.08%</strong> variability of target that is a better indication with respect to the multiple linear regression model with TV and Radio as predictor. The Residual standard error for the model is <strong>1.404</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mlr1, opr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Sales ~ TV + Radio
Model 2: Sales ~ poly(TV, 2) + poly(Radio, 2) + TV:Radio
  Res.Df    RSS Df Sum of Sq     F    Pr(&gt;F)    
1    148 441.63                                 
2    145 285.85  3    155.78 26.34 1.168e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Since the p-value for testing the null hypothesis (<span class="math inline">\(1.168e-13\)</span>) is significantly less than 0.05, hence we have sufficient evidence to reject the null hypothesis and accept the alternative. Therefore, the improvement in the Adjusteed R2 is statistically significant. To have bases covered, we will also try fitting a third order orthogonal polynomial regression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>opr2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> <span class="fu">poly</span>(TV,<span class="dv">3</span>) <span class="sc">+</span> <span class="fu">poly</span>(Radio,<span class="dv">3</span>) <span class="sc">+</span> TV<span class="sc">:</span>Radio, <span class="at">data=</span>train)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(opr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ poly(TV, 3) + poly(Radio, 3) + TV:Radio, 
    data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5998 -0.6947  0.0119  0.6711  3.2824 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      1.359e+01  3.300e-01  41.183  &lt; 2e-16 ***
poly(TV, 3)1     4.481e+01  2.613e+00  17.148  &lt; 2e-16 ***
poly(TV, 3)2    -8.288e+00  1.401e+00  -5.915 2.34e-08 ***
poly(TV, 3)3     9.420e-01  1.393e+00   0.676  0.50011    
poly(Radio, 3)1  8.850e+00  2.907e+00   3.044  0.00278 ** 
poly(Radio, 3)2  3.470e+00  1.392e+00   2.493  0.01380 *  
poly(Radio, 3)3  4.148e+00  1.401e+00   2.962  0.00359 ** 
TV:Radio         4.494e-04  9.016e-05   4.984 1.78e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.369 on 143 degrees of freedom
Multiple R-squared:  0.9372,    Adjusted R-squared:  0.9342 
F-statistic: 305.1 on 7 and 143 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>It is clear from the results above that third order of TV predictor is not statistically significant (p-value &gt; 0.05). Hence, we won’t include this in the model. Hence, the fit is -</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>opr3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> <span class="fu">poly</span>(TV,<span class="dv">2</span>) <span class="sc">+</span> <span class="fu">poly</span>(Radio,<span class="dv">3</span>) <span class="sc">+</span> TV<span class="sc">:</span>Radio, <span class="at">data=</span>train)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(opr3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ poly(TV, 2) + poly(Radio, 3) + TV:Radio, 
    data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.7550 -0.6920 -0.0132  0.7186  3.2248 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      1.356e+01  3.270e-01  41.478  &lt; 2e-16 ***
poly(TV, 2)1     4.462e+01  2.593e+00  17.206  &lt; 2e-16 ***
poly(TV, 2)2    -8.262e+00  1.398e+00  -5.910 2.37e-08 ***
poly(Radio, 3)1  8.518e+00  2.860e+00   2.979  0.00340 ** 
poly(Radio, 3)2  3.473e+00  1.389e+00   2.500  0.01353 *  
poly(Radio, 3)3  4.201e+00  1.396e+00   3.010  0.00308 ** 
TV:Radio         4.571e-04  8.926e-05   5.121 9.58e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.367 on 144 degrees of freedom
Multiple R-squared:  0.937, Adjusted R-squared:  0.9344 
F-statistic: 357.2 on 6 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Checking all the assumptions of regression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linearity Assumption</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(opr3 ,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Homoscedasticity Assumption </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_test_score</span>(opr3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Score Test for Heteroskedasticity
 ---------------------------------
 Ho: Variance is homogenous
 Ha: Variance is not homogenous

 Variables: fitted values of Sales 

        Test Summary         
 ----------------------------
 DF            =    1 
 Chi2          =    1.497247 
 Prob &gt; Chi2   =    0.2210954 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Autocorrelation Assumption </span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(opr3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1      -0.0442372      2.076031    0.57
 Alternative hypothesis: rho != 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normality Assumption</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(opr3<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  opr3$residuals
W = 0.98162, p-value = 0.04121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multicolinearity Assumption</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(opr3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                   GVIF Df GVIF^(1/(2*Df))
poly(TV, 2)    3.764510  2        1.392923
poly(Radio, 3) 4.609044  3        1.290036
TV:Radio       7.526778  1        2.743497</code></pre>
</div>
</div>
</section>
<section id="making-predictions" class="level4">
<h4 class="anchored" data-anchor-id="making-predictions">Making Predictions</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>prediction <span class="ot">&lt;-</span> opr3 <span class="sc">%&gt;%</span> <span class="fu">predict</span>(test)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Cheking performance by calculating R2, RMSE, and MAE</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>( <span class="at">R2 =</span> <span class="fu">R2</span>(prediction, test<span class="sc">$</span>Sales), </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE =</span> <span class="fu">RMSE</span>(prediction, test<span class="sc">$</span>Sales),</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">MAE =</span> <span class="fu">MAE</span>(prediction, test<span class="sc">$</span>Sales))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         R2     RMSE       MAE
1 0.9395374 1.264048 0.9417405</code></pre>
</div>
</div>
<p>The R2 we obtain seems like a decent fit, however this result is based on one test data set. Hence, we cannot be certain that the model will perform better on unseen data. Therefore, we will use K-fold cross validation to test the performance of model on a different test data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>train_control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>model_cv <span class="ot">&lt;-</span> <span class="fu">train</span>(Sales <span class="sc">~</span> <span class="fu">poly</span>(TV,<span class="dv">2</span>) <span class="sc">+</span> <span class="fu">poly</span>(Radio,<span class="dv">3</span>) <span class="sc">+</span> TV<span class="sc">:</span>Radio, <span class="at">data=</span>data, <span class="at">method =</span> <span class="st">"lm"</span>,                    <span class="at">trControl =</span> train_control)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_cv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

199 samples
  2 predictor

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 179, 179, 179, 179, 180, 178, ... 
Resampling results:

  RMSE      Rsquared   MAE      
  1.298474  0.9392671  0.9752946

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
</div>
<p>This model captures almost <strong>94%</strong> variability available in the target on average. Therefore, we can say that this is still a decent fit.</p>
<p>To summarize, we looked at Simple Linear Regression and expanded those to Multiple Linear Regression to find a better fit. To cover all bases, we also tried to fit a polynomial regression model. Ultimately, we found a better fit by comparing variability and p-values. In conclusion, linear and non-linear regression stand as pillars for modeling relationships and making predictions. Understanding when to choose one over the other and how to interpret the results is essential.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>